### PR TITLE
Update demo.liquid

### LINKED ISSUE #210: Playground uses filter that doesn't seem to work
I noticed the playground default code is using `| capitalize` which seems to not do anything. The playground still works fine I guess, but seeing that filter there and it not doing anything may confuse folks.

### PR DESCRIPTION
**Pull request by cfjedimaster**
docs: Fixes issue with typo in filter

### CODE REVIEW

**Comment by harttle** [comment]
Try resubmit with commit message like `docs: blabla`

**Comment by cfjedimaster** [comment]
Edited here - will that do it?

**Comment by harttle** [comment]
Never mind, I'll fix it for you in the next commit.

**Comment by cfjedimaster** [comment]
Ok sorry - my GitFu is weak. Hope this helps!

**Pull request merged**
